# -*- coding: utf-8 -*-
"""FaceRecognitionSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Th2-KgDYF2RpzOc_pyYNXXb2ZO1I0X21
"""

# Title : Face Recognition System using LFW Dataset
from google.colab import drive
drive.mount('/content/drive')

# Install required Packages
!pip install tensorflow mtcnn scikit-learn tensorflow_hub

import os
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from mtcnn import MTCNN
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import cv2
from tqdm.notebook import tqdm
import requests
import tarfile
import random
import pickle

class FaceRecognitionSystem:
  def __init__(self):
    self.detector = MTCNN()
    #Load Efficient Net Model directly using keraslayer wrapper
    self.facenet_model_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2')
    self.required_size = (160,160)
    self.embeddings = []
    self.labels = []
    self.le = LabelEncoder()
    self.classifier = SVC(kernel="linear", C=0.1, probability=True)

  def _extract_face(self, image):
    faces = self.detector.detect_faces(image)
    if not faces:
      return None

    x1, y1, width, height = faces[0]['box']
    x2, y2 = x1 + width, y1 + height

    face = image[y1:y2, x1:x2]
    face = cv2.resize(face, self.required_size)
    return face

  def _get_embedding(self, face):
    face = face.astype('float32') / 255.0 # Normalize
    face = (face - 0.5) * 2.0 # Scale to [-1, 1] if required

    # Add batch dimension and get embedding
    face_tensor = tf.convert_to_tensor([face])
    embedding = self.facenet_model_layer(face_tensor)

    return embedding.numpy()[0]


  def process_dataset(self, dataset_path, max_samples_per_person=5):
    person_samples = {}

    # First, find eligible people (those with enough samples)
    for person_name in os.listdir(dataset_path):
      person_dir = os.path.join(dataset_path, person_name)
      if os.path.isdir(person_dir):
        images = [f for f in os.listdir(person_dir)
          if f.endswith(('.jpg', '.jpeg', '.png'))]

        if len(images) >= max_samples_per_person:
          person_samples[person_name] = images[:max_samples_per_person]

    print(f"Found {len(person_samples)} people with sufficient samples")

    # Process faces for each eligible person
    for person_name, images in tqdm(person_samples.items(), desc="Processing People"):
      sucessful_embeddings = 0
      for image_name in images:
        try:
          image_path = os.path.join(dataset_path, person_name, image_name)
          image = cv2.imread(image_path)
          if image is None:
            continue

          image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
          face = self._extract_face(image)

          if face is not None:
            embedding = self._get_embedding(face)
            self.embeddings.append(embedding)
            self.labels.append(person_name)
            sucessful_embeddings += 1

        except Exception as e:
          print(f"Error Processing {image_path}: {str(e)}")

      if sucessful_embeddings > 0:
        print(f"Processed {sucessful_embeddings} images for {person_name}")

  def train_classifier(self):
    if len(self.embeddings) == 0:
      print("No embeddings to train on!!!")
      return None

    X = np.array(self.embeddings)
    encoded_labels = self.le.fit_transform(self.labels)

    X_train, X_test, Y_train, Y_test = train_test_split(
        X, encoded_labels, test_size=0.2, random_state=42
    )

    self.classifier.fit(X_train, Y_train)

    Y_pred = self.classifier.predict(X_test)

    accuracy = accuracy_score(Y_test, Y_pred)

    return {
        "accuracy": accuracy,
        "X_train": X_train,
        "X_test": X_test,
        "Y_train": Y_train,
        "Y_test": Y_test,
        "Y_pred": Y_pred,
    }

# Plotting the results
def plot_results(results):
  if results is None:
    print("No results to plot!!!")
    return

  plt.figure(figsize=(15, 5))

  plt.subplot(1, 2, 1)
  plt.title("Training Data Distribution")
  unique, counts = np.unique(results["Y_train"], return_counts=True)
  plt.bar(unique[:10], counts[:10]) #plot only first 10 classes for visibility
  plt.xlabel("Person_ID (first 10)")
  plt.ylabel("Number of Samples")

  plt.subplot(1, 2, 2)
  plt.title(f"Model Accuracy: {results['accuracy']:.2%}")
  cm = tf.math.confusion_matrix(results['Y_test'], results['Y_pred']).numpy()
  plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
  plt.colorbar()
  plt.xlabel('Predicted label')
  plt.ylabel('True label')

  plt.tight_layout()
  plt.show()

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/archive.zip -d /content/drive/MyDrive/

!ls /content/drive/MyDrive/lfw-deepfunneled

!ls /content/drive/MyDrive/lfw-deepfunneled/lfw-deepfunneled | head

try:
  # Set the dataset path based on previous unzip operation
  dataset_path = "/content/drive/MyDrive/lfw-deepfunneled/lfw-deepfunneled"

  # Initialize system and process dataset
  print("Initializing the Face Recognition System...")
  face_system = FaceRecognitionSystem()

  print("Processing Data...")
  face_system.process_dataset(dataset_path, max_samples_per_person=2)

  # Train Classifier and get results
  print(f"Training classifier on {len(face_system.embeddings)} samples...")
  results = face_system.train_classifier()

  if results is not None:
    # Ensure matplotlib is imported for plotting
    import matplotlib.pyplot as plt
    # Ensure classification_report is imported for printing report
    from sklearn.metrics import classification_report
    plot_results(results) #plot and display the results

    # Print Classification report
    Y_true = face_system.le.inverse_transform(results['Y_test'])
    Y_pred = face_system.le.inverse_transform(results['Y_pred'])
    print("\nClassification Report")
    print(classification_report(Y_true, Y_pred))

    # Save Model
    save_path = '/content/drive/MyDrive/face_recognition_model.pkl'
    if os.path.exists('/content/drive'):
      import pickle
      model_data = {
          'Classifier': face_system.classifier,
          'Label_Encoder': face_system.le
      }
      with open(save_path, 'wb') as f:
        pickle.dump(model_data, f)
      print(f"Model saved to Google Drive: {save_path}")
    else:
      print("Google Drive not mounted or path not found. Model not saved.")

  else:
    print("Training failed due to lack of Data")

except Exception as e:
  print(f"An Error Occurred: {str(e)}")
  raise

class FaceRecognitionDemo:
  def __init__(self, model_path):
    # Load the saved ,odel and components
    with open(model_path, 'rb') as f:
      model_data = pickle.load(f)

    self.classifier = model_data['Classifier']
    self.le = model_data['Label_Encoder']
    self.detector = MTCNN()

    #Load Efficient Net Model directly using keraslayer wrapper
    self.facenet_model_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2')
    self.required_size = (160,160)

  def process_image(self, image):
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    faces = self.detector.detect_faces(rgb_image)

    if not faces:
        return None, None

    x1, y1, width, height = faces[0]['box']

    #  Prevent negative coordinates
    x1 = max(0, x1)
    y1 = max(0, y1)

    x2 = x1 + width
    y2 = y1 + height

    face = rgb_image[y1:y2, x1:x2]
    face_resized = cv2.resize(face, self.required_size)

    # Normalize to [-1, 1]
    face_array = face_resized.astype('float32') / 255.0
    face_normalized = (face_array - 0.5) * 2.0

    # Generate embedding
    face_tensor = tf.convert_to_tensor([face_normalized])
    embedding = self.facenet_model_layer(face_tensor).numpy()[0]

    return embedding, (x1, y1, x2, y2)


  def predict(self, image):
    embedding, face_box = self.process_image(image)
    if embedding is None:
      return None, None, None

    # Predict
    pred_proba = self.classifier.predict_proba([embedding])[0]
    pred_class = np.argmax(pred_proba)
    confidence = pred_proba[pred_class]
    predicted_name = self.le.inverse_transform([pred_class])[0]

    return predicted_name, confidence, face_box

def get_random_test_images(lfw_path, num_images=5):
  all_people = [d for d in os.listdir(lfw_path) if os.path.isdir(os.path.join(lfw_path, d))]
  selected_people = random.sample(all_people, num_images)

  test_images = []
  for person in selected_people:
    person_dir = os.path.join(lfw_path, person)
    images = os.listdir(person_dir)
    selected_image = random.choice(images)
    image_path = os.path.join(person_dir, selected_image)
    image = cv2.imread(image_path)
    test_images.append((person, image))

  return test_images

def display_results(test_images, predictions):
  plt.figure(figsize=(20,4))
  for i, ((true_name, image), (pred_name, confidence, face_box)) in enumerate(zip(test_images, predictions)):
    plt.subplot(1, len(test_images), i+1)

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    if face_box:
      x1, y1, x2, y2 = face_box
      cv2.rectangle(image_rgb, (x1, y1), (x2, y2), (0, 255, 0), 2)

    plt.imshow(image_rgb)
    if pred_name is None:
      result_text = f"True: {true_name}\nNo Face Detected"
    else:
      result_text = f"True: {true_name}\nPred_name: {pred_name}\nConfidence: {confidence:.2%}"
    plt.title(result_text, fontsize=10)
    plt.axis('off')

  plt.tight_layout()
  plt.show()

try:
  # Mount Google Drive to access the saved model
    from google.colab import drive
    drive.mount('/content/drive')

    model_path = '/content/drive/MyDrive/face_recognition_model.pkl'

  # Initialize the demo system
    print("Initializing demo system...")
    demo_system = FaceRecognitionDemo(model_path)

  # Get random test images
    print("Getting test images...")
    lfw_path = "/content/drive/MyDrive/lfw-deepfunneled/lfw-deepfunneled"
    test_images = get_random_test_images(lfw_path, num_images=5)

  # Make predictions
    print("Making predictions...")
    predictions = []

    for true_name, image in test_images:
        pred_name, confidence, face_box = demo_system.predict(image)
        predictions.append((pred_name, confidence, face_box))

   # Display results
    print("Displaying results...")
    display_results(test_images, predictions)

  # Calculate and display metrics
    correct_predictions = sum(
        1
        for (true_name, _), (pred_name, _, _) in zip(test_images, predictions)
        if pred_name is not None and true_name == pred_name
    )

    total_predictions = len(test_images)
    accuracy = correct_predictions / total_predictions if total_predictions > 0 else 0

    print("\n========== METRICS ==========")
    print(f"Accuracy: {accuracy:.2%}")
    print(f"Correct: {correct_predictions}/{total_predictions}")
    print("=============================\n")

    # Detailed Per-Image Output

    for (true_name, _), (pred_name, confidence, _) in zip(test_images, predictions):

        if pred_name is None:
            print(f"True: {true_name:<20} → No face detected")
        else:
            status = "✓" if true_name == pred_name else "✗"
            print(f"{status} True: {true_name:<20} "
                  f"Predicted: {pred_name:<20} "
                  f"Confidence: {confidence:.2%}")

except Exception as e:
    print(f"An error occurred: {str(e)}")
    raise

print(type(model_data))
print(model_data)

