# -*- coding: utf-8 -*-
"""Facial_recognition_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159HUgZDgvztxy7HIkhSX2Qg8qGmDoUXR
"""

# Title: Face Recognition System using LFW Dataset
from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install tensorflow mtcnn scikit-learn tensorflow_hub

!pip install lz4

from sklearn.datasets import fetch_lfw_people
import os
import shutil

print("Fetching LFW dataset via Scikit-Learn cloud mirror...")
lfw_raw = fetch_lfw_people(download_if_missing=True, funneled=False)

source_dir = os.path.expanduser('~/scikit_learn_data/lfw_home/lfw')

# Make sure old paths are clear before moving
!rm -rf /content/lfw
shutil.move(source_dir, '/content/lfw')

if os.path.exists('/content/lfw'):
    print("\nSUCCESS! Dataset successfully built at: /content/lfw")

!rm -rf lfw /content/lfw
!unzip -q /content/drive/MyDrive/lfw-deepfunneled.zip -d /content/
!mv /content/lfw-deepfunneled /content/lfw
!ls -d /content/lfw

import os
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from mtcnn import MTCNN
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import cv2
from tqdm.notebook import tqdm
import requests
import tarfile
import random
import pickle
from google.colab import drive
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

import os
import random
import cv2
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from mtcnn import MTCNN
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from tqdm import tqdm

class FaceRecognitionSystem:
    def __init__(self):
        self.detector = MTCNN()
        # Load EfficientNet model directly using KerasLayer wrapper
        self.facenet_model_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2')
        self.required_size = (160, 160)
        self.embeddings = []
        self.labels = []
        self.le = LabelEncoder()
        self.classifier = None

    def _extract_face(self, image):
        faces = self.detector.detect_faces(image)
        if not faces:
            return None

        x1, y1, width, height = faces[0]['box']
        x2, y2 = x1 + width, y1 + height

        face = image[y1:y2, x1:x2]
        face = cv2.resize(face, self.required_size)
        return face

    def _get_embedding(self, face):
        # Preprocess the face image
        face = face.astype('float32') / 255.0 # Normalize pixel values
        face = (face - 0.5) * 2.0  # Scale to [-1,1] if required

        # Add batch dimension and get embedding
        face_tensor = tf.convert_to_tensor([face])
        embedding = self.facenet_model_layer(face_tensor)
        return embedding.numpy()[0]

    def process_dataset(self, dataset_path, max_samples_per_person=20):
        person_samples = {}

        # First, find eligible people (those with enough samples)
        for person_name in os.listdir(dataset_path):
            person_dir = os.path.join(dataset_path, person_name)
            if os.path.isdir(person_dir):
                images = [f for f in os.listdir(person_dir)
                          if f.endswith(('.jpg', '.jpeg', '.png'))][:max_samples_per_person]
                if len(images) >= 20:  # Only include people with at least 5 images
                    person_samples[person_name] = images

        print(f"Found {len(person_samples)} people with sufficient samples")

        # Process faces for each eligible person
        for person_name, images in tqdm(person_samples.items(), desc="Processing people"):
            successful_embeddings = 0
            for image_name in images:
                try:
                    image_path = os.path.join(dataset_path, person_name, image_name)
                    image = cv2.imread(image_path)
                    if image is None:
                        continue

                    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                    face = self._extract_face(image)

                    if face is not None:
                        embedding = self._get_embedding(face)
                        self.embeddings.append(embedding)
                        self.labels.append(person_name)
                        successful_embeddings += 1
                except Exception as e:
                    print(f"Error processing {image_path}: {str(e)}")

            if successful_embeddings > 0:
                print(f"Processed {successful_embeddings} images for {person_name}")

    def train_classifier(self):
        if len(self.embeddings) == 0:
            print("No embeddings to train on!")
            return None

        X = np.array(self.embeddings)
        encoded_labels = self.le.fit_transform(self.labels)

        X_train, X_test, y_train, y_test = train_test_split(
            X, encoded_labels, test_size=0.2, random_state=42
        )

        print("Optimizing SVM Brain via Grid Search...")

        param_grid = {
            'C': [0.1, 1, 10, 100],
            'gamma': ['scale', 'auto', 0.001, 0.01],
            'kernel': ['linear', 'rbf']
        }

        grid_search = GridSearchCV(
            estimator=SVC(probability=True),
            param_grid=param_grid,
            cv=3,
            n_jobs=-1,
            verbose=1
        )

        grid_search.fit(X_train, y_train)

        self.classifier = grid_search.best_estimator_

        print(f"Best Configuration Discovered: {grid_search.best_params_}")

        y_pred = self.classifier.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)

        return {
            'accuracy': accuracy,
            'X_train': X_train,
            'X_test': X_test,
            'y_train': y_train,
            'y_test': y_test,
            'y_pred': y_pred
        }

def plot_results(results):
    if results is None:
        print("No results to plot!")
        return

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 2, 1)
    plt.title('Training Data Distribution')
    unique, counts = np.unique(results['y_train'], return_counts=True)
    plt.bar(unique[:10], counts[:10])  # Plot only first 10 classes for visibility
    plt.xlabel('Person ID (first 10)')
    plt.ylabel('Number of samples')

    plt.subplot(1, 2, 2)
    plt.title(f"Model Accuracy: {results['accuracy']:.2%}")
    cm = tf.math.confusion_matrix(results['y_test'], results['y_pred'])
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.colorbar()
    plt.xlabel('Predicted label')
    plt.ylabel('True label')

    plt.tight_layout()
    plt.show()

try:
    # Initialize system and process dataset
    print("Initializing Face Recognition System...")
    face_system = FaceRecognitionSystem()

    print("Processing dataset...")
    dataset_path = '/content/lfw'
    face_system.process_dataset(dataset_path, max_samples_per_person=20)

    # Train classifier and get results
    print(f"Training classifier on {len(face_system.embeddings)} samples...")
    results = face_system.train_classifier()

    if results is not None:
        # Plot and display results
        plot_results(results)

        # Print classification report
        y_true = face_system.le.inverse_transform(results['y_test'])
        y_pred = face_system.le.inverse_transform(results['y_pred'])
        print("\nClassification Report:")
        print(classification_report(y_true, y_pred))

        # Save model
        save_path = '/content/drive/MyDrive/face_recognition_model.pkl'
        if os.path.exists('/content/drive'):
            import pickle
            model_data = {
                'classifier': face_system.classifier,
                'label_encoder': face_system.le
            }
            with open(save_path, 'wb') as f:
                pickle.dump(model_data, f)
            print(f"Model saved to Google Drive: {save_path}")
    else:
        print("Training failed due to lack of data.")

except Exception as e:
    print(f"An error occurred: {str(e)}")
    raise



class FaceRecognitionDemo:
    def __init__(self, model_path):
        # Load the saved model and components
        with open(model_path, 'rb') as f:
            model_data = pickle.load(f)

        self.classifier = model_data['classifier']
        self.le = model_data['label_encoder']
        self.detector = MTCNN()

        # Load EfficientNet model using KerasLayer
        self.facenet_model_layer = hub.KerasLayer('https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2')
        self.required_size = (160, 160)

    def process_image(self, image):
        rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        faces = self.detector.detect_faces(rgb_image)

        if not faces:
            return None, None

        x1, y1, width, height = faces[0]['box']
        x2, y2 = x1 + width, y1 + height

        face = rgb_image[y1:y2, x1:x2]
        face_resized = cv2.resize(face, self.required_size)

        # Normalize and scale image to [-1, 1]
        face_array = face_resized.astype('float32') / 255.0
        face_normalized = (face_array - 0.5) * 2.0

        # Prepare input for EfficientNet
        face_tensor = tf.convert_to_tensor([face_normalized])
        embedding = self.facenet_model_layer(face_tensor).numpy()[0]

        return embedding, (x1, y1, x2, y2)

    def predict(self, image):
        embedding, face_box = self.process_image(image)
        if embedding is None:
            return None, None, None

        # Predict
        pred_proba = self.classifier.predict_proba([embedding])[0]
        pred_class = np.argmax(pred_proba)
        confidence = pred_proba[pred_class]
        predicted_name = self.le.inverse_transform([pred_class])[0]

        return predicted_name, confidence, face_box

def get_random_test_images(face_system, lfw_path, num_images=5):
    # 1. Grab only the names of people the model actually trained on!
    eligible_people = list(face_system.le.classes_)

    # 2. Randomly select from the known population
    selected_people = random.sample(eligible_people, num_images)

    test_images = []
    for person in selected_people:
        person_dir = os.path.join(lfw_path, person)
        images = [f for f in os.listdir(person_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]

        selected_image = random.choice(images)
        image_path = os.path.join(person_dir, selected_image)
        image = cv2.imread(image_path)
        test_images.append((person, image))

    return test_images

def display_results(test_images, predictions):
    plt.figure(figsize=(20, 4))
    for i, ((true_name, image), (pred_name, confidence, face_box)) in enumerate(zip(test_images, predictions)):
        plt.subplot(1, len(test_images), i+1)

        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        if face_box:
            x1, y1, x2, y2 = face_box
            cv2.rectangle(image_rgb, (x1, y1), (x2, y2), (0, 255, 0), 2)

        plt.imshow(image_rgb)
        if pred_name is None:
            result_text = f"True: {true_name}\nNo face detected"
        else:
            result_text = f"True: {true_name}\nPred: {pred_name}\nConf: {confidence:.2%}"
        plt.title(result_text, fontsize=10)
        plt.axis('off')

    plt.tight_layout()
    plt.show()

try:
    # Mount Google Drive to access the saved model
    drive.mount('/content/drive')
    model_path = '/content/drive/MyDrive/face_recognition_model.pkl'

    # Initialize the demo system
    print("Initializing demo system...")
    demo_system = FaceRecognitionDemo(model_path)

    # Get random test images
    print("Getting test images...")
    lfw_path = '/content/lfw'
    test_images = get_random_test_images(demo_system, lfw_path, num_images=5)

    # Make predictions
    print("Making predictions...")
    predictions = []
    for _, image in test_images:
        pred_name, confidence, face_box = demo_system.predict(image)
        predictions.append((pred_name, confidence, face_box))

    # Display results
    print("Displaying results...")
    display_results(test_images, predictions)

    # Calculate and display metrics
    correct_predictions = sum(1 for (true_name, _), (pred_name, _, _)
                                in zip(test_images, predictions)
                                if pred_name is not None and true_name == pred_name)
    total_predictions = sum(1 for (_, _, _) in predictions if _ is not None)

    if total_predictions > 0:
        accuracy = correct_predictions / total_predictions
        print(f"\nTest Accuracy: {accuracy:.2%}")
    else:
        print("\nNo valid predictions made")

    # Display detailed results
    print("\nDetailed Results:")
    for (true_name, _), (pred_name, confidence, _) in zip(test_images, predictions):
        if pred_name is None:
            print(f"✗ True: {true_name:<20} No face detected")
        else:
            status = "✓" if true_name == pred_name else "✗"
            print(f"{status} True: {true_name:<20} Predicted: {pred_name:<20} Confidence: {confidence:.2%}")

except Exception as e:
    print(f"An error occurred: {str(e)}")
    raise

